#!/usr/bin/python3
import sys
import random
import pyperclip as pc
from termcolor import colored


def main():
    # Check if there are parameters set
    if len(sys.argv) < 2:
        print("Please insert a string after the command")
        quit()

    # Add first parameter to string
    # In case of multiple parameters, add them separated by a space
    string = sys.argv[1]
    for arg in sys.argv[2:]:
        string += " "
        string += arg

    # Algorithm
    new_string = "";
    random_int_range = 10
    for i, c in enumerate(string.lower()):
        random_int = random.randint(1,random_int_range)
        if (random_int <= 5):
            new_string += c.swapcase()
            random_int_range += 1
        else:
            new_string += c
            random_int_range -= 1


    print("\n" + new_string)
    pc.copy(new_string)
    print(colored("Output is copied to the clipboard!", "green"))

if __name__ == '__main__':
    main()
